### ISSUE TITLE
Partial matching warnings in tests

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3pipelines#604] opened 2021-09-26 08:09 UTC
```
── Warning (test_pipeop_textvectorizer.R:26:3): PipeOpTextVectorizer - basic properties ──
partial argument match of 'remove' to 'remove_padding'
```

**Comment by mb706** [comment] 2021-09-29 10:22
Duplicate of https://github.com/mlr-org/mlr3pipelines/issues/581

**Closed by mb706** 2021-09-29 10:22 UTC
Labels: Type: Maintenance
