### ISSUE TITLE
ppl_branch: Why do we default to integer for "selection", and not the id?

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#430] opened 2020-05-27 18:15 UTC
See above.

**Comment by sumny** [comment] 2020-05-28 15:00
> Additionally: Perhaps expose branch / unbranch id to be overwritten

+1 for this. Users may want to chain branches within a Graph

**Comment by mb706** [comment] 2020-06-21 01:06
> Perhaps expose branch / unbranch id to be overwritten

there is the `prefix_branchops` parameter

**Comment by mb706** [comment] 2020-06-21 01:11
> Why do we default to integer for "selection", and not the id

Do you mean, why is
```r
pipeline_branch(list(po("nop"), po("pca")))$param_set$params$branch.selection
```
a `ParamInt`? If so the problem is that it is difficult to generally infer the supposed IDs for branches with more than one pipeop, and having special treatment for single-element-graphs is ugly. To get named branches, the path is
```r
pipeline_branch(list(A = po("nop"), B = po("pca")))
```
which gets
```r
pipeline_branch(list(A = po("nop"), B = po("pca")))$param_set$params$branch.selection
```
which is a `ParamFct`.

**Comment by pfistfl** [comment] 2020-06-22 08:54
This were issues raised by bernd in preparation to the whyr2020 talk.

- Imho it is slightly weird fort `branch.selection` to be a `ParamInt`, perhaps we could have it be a `ParamFct` "1", "2", ... ? Than at least the type would always be consistent?

- The branch pre- and postfixing is good, but we might simply wanna set the id's in some case, e.g. for visual presentation. I guess this would be a relatively simple change that does not really hurt / interfere with the rest of the functionality?

**Comment by mb706** [comment] 2020-06-22 10:45
> The branch pre- and postfixing is good, but we might simply wanna set the id's in some case, e.g. for visual presentation

That sounds like a pretty rare case that could be solved with `$set_names()` and would bloat the API if we add another parameter to the `pipeline_branch()` just for this.

**Comment by mb706** [comment] 2020-08-31 14:28
Closing this, if someone disagrees feel free to open again and we can discuss.

**Closed by mb706** 2020-08-31 14:28 UTC
