### ISSUE TITLE
as.data.table(mlr_pipeops) throws error

### ISSUE THREAD

**Issue by jonnybaik** [mlr-org/mlr3pipelines#286] opened 2019-10-17 22:32 UTC
I am following the detailed introduction for the mlr3pipelines package [here](https://mlr3pipelines.mlr-org.com/articles/introduction.html#where-to-get-pipeops) and I cannot seem to get the table of available pipelines as shown in the documentation with `as.data.table(mlr_pipeops)`.

```R
library(mlr3)
library(mlr3pipelines)
as.data.table(mlr_pipeops)
# Error in check_list(x, types = "formula", names = "unique") %&&% Reduce(`%&&%`,  : 
#   could not find function "%&&%"
```

It looks like one of the predefined PipeOp's uses a function, `%&&%`, that has not been exported. Running the `as.data.table.DictionaryPipeOp` function line by line, it appears that the "mutate" PipeOp may be the culprit.

```R
mlr_pipeops$get("mutate")
# Error in check_list(x, types = "formula", names = "unique") %&&% Reduce(`%&&%`,  : 
#   could not find function "%&&%"
```

My session info:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/libf77blas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8   
 [6] LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlr3pipelines_0.1.0 mlr3_0.1.3         

loaded via a namespace (and not attached):
 [1] paradox_0.1.0     compiler_3.5.1    backports_1.1.5   R6_2.4.0          lgr_0.3.3         tools_3.5.1       withr_2.1.2       rstudioapi_0.10  
 [9] crayon_1.3.4      uuid_0.1-2        data.table_1.12.4 checkmate_1.9.4   mlr3misc_0.1.5    digest_0.6.21     packrat_0.5.0    
```

**Comment by jonnybaik** [comment] 2019-10-17 22:50
Setting ``%&&%` <- `Matrix::%&%`` seems to work:

```
> `%&&%` <- Matrix::`%&%`
> as.data.table(mlr_pipeops)
                key      packages input.num output.num input.type.train input.type.predict output.type.train output.type.predict
 1:          boxcox bestNormalize         1          1             Task               Task              Task                Task
 2:          branch                       1         NA                *                  *                 *                   *
 3:           chunk                       1         NA             Task               Task              Task                Task
 4:  classbalancing                       1          1             Task               Task              Task                Task
 5:      classifavg         stats        NA          1             NULL  PredictionClassif              NULL   PredictionClassif
 6:        colapply                       1          1             Task               Task              Task                Task
[...]
```

**Comment by mllg** [comment] 2019-10-22 08:53
IIRC, I was able to reproduce this some days ago on a different system. Works for me now and `%&&%` is defined in `R/utils.R`. That's odd.

@mb706 Can you try to reproduce please?

**Comment by mb706** [comment] 2019-10-22 09:26
Also couldn't reproduce it yet but will look into it more.

**Comment by mb706** [comment] 2021-09-29 19:05
Closing as per https://github.com/mlr-org/mlr3pipelines/issues/287#issuecomment-930461932

**Closed by mb706** 2021-09-29 19:05 UTC
Labels: Status: Available, Type: Bug, Type: Maintenance, Priority: Medium
